CREATE OR REPLACE FUNCTION MZONTUL.CLASS_SD(E_YEAR IN VARCHAR2,TERM IN SMALLINT,LECTURE_CODE IN VARCHAR2)
RETURN NUMBER IS
AVG_ NUMBER(5,2);
SD NUMBER(5,2);
DIFF2 NUMBER(5,2);
N NUMBER(5);
BEGIN  
  SELECT AVG(T.AVERAGE)INTO AVG_
  FROM MZONTUL.TRANSCRIPT T
  WHERE T.E_YEAR=E_YEAR AND T.TERM=TERM AND T.LECTURE_CODE=LECTURE_CODE; 
  
  SELECT SUM(POWER(T.AVERAGE-AVG_,2)),COUNT(*)INTO DIFF2,N 
  FROM MZONTUL.TRANSCRIPT T
  WHERE T.E_YEAR=E_YEAR AND T.TERM=TERM AND T.LECTURE_CODE=LECTURE_CODE;
  
  IF N>=30 THEN  
   N:=N-1;
  END IF;
     
  SELECT SQRT(DIFF2/N) INTO SD FROM DUAL; 
  
  RETURN SD;
END CLASS_SD;

DECLARE 
  SD NUMBER(5,2);
BEGIN
  SELECT MZONTUL.CLASS_SD('2009-2010',1,'SENG101') INTO SD FROM DUAL;
  DBMS_OUTPUT.PUT_LINE(SD);
END;