CREATE OR REPLACE FUNCTION MZONTUL.FACTORIAL2(N IN NUMBER) RETURN NUMBER IS
  i NUMBER := 1;
  F NUMBER:=1;
BEGIN   
    FOR i IN 1..N LOOP           
        F:=F*i;        
    END LOOP;
    RETURN F;
END;

SELECT MZONTUL.FACTORIAL2(6) FROM DUAL;
SELECT SYSDATE FROM DUAL;