CREATE OR REPLACE PROCEDURE MZONTUL.FACTORIAL(N IN NUMBER,RESULT OUT NUMBER)IS
    i NUMBER := 1;
    F NUMBER:=1;
BEGIN
   
    FOR i IN 1..N LOOP           
        F:=F*i;        
    END LOOP;
    RESULT:=F;
END;
DECLARE
  RESULT NUMBER(38);
BEGIN
  MZONTUL.FACTORIAL(6,RESULT);
  DBMS_OUTPUT.PUT_LINE(RESULT);
END;